name: Versioning

on:
  push:
    branches:
    - development
    - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version
        id: bump-version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          pre_release_branches: development
          append_to_pre_release_tag: dev
          custom_release_rules: major:major, minor:minor

      - run: |
          echo ${{ steps.bump-version.outputs.new_tag }}
          echo ${{ steps.bump-version.outputs.new_version }}
          echo ${{ steps.bump-version.outputs.previous_tag }}
          echo ${{ steps.bump-version.outputs.previous_version }}
          echo ${{ steps.bump-version.outputs.release_type }}
          echo ${{ steps.bump-version.outputs.changelog }}

#      - name: Create release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.get-version.outputs.previous_tag }}
#          release_name: Release ${{ steps.get-version.outputs.previous_tag }}
#        if: ${{ github.ref_name == 'main' }}
