name: Test Versioning

on:
  push:
    branches:
    - development
    - staging
    - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version
        id: bump-version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: development
          custom_release_rules: major:major, minor:minor
        if: ${{ github.ref_name == 'development' }}

      - name: Get version
        id: get-version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: development
          custom_release_rules: major:major, minor:minor
          default_bump: false
          dry_run: true
        if: ${{ github.ref_name == 'staging' || github.ref_name == 'main' }}
      - run: echo "Version ${{ steps.get-version.outputs.previous_tag }}"
        if: ${{ github.ref_name == 'staging' || github.ref_name == 'main' }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.previous_tag }}
          release_name: Release ${{ steps.get-version.outputs.previous_tag }}
        if: ${{ github.ref_name == 'main' }}
